version: 1.0.{build}
build:
  verbosity: minimal
  project: build-tests.sln

environment:
  api_key:
    secure: plhX9LRt4yL5H2VkL91sLRU90FFZbkvkYFudMEanX3A=

after_build:
  - cmd: C:/Tools/xUnit20 "C:/Projects/build-tests/bin/debug/build-tests.dll"
