version: 1.0.{build}


environment:
  APPVEYOR_BUILD_WORKER_CLOUD:  test-workers-v2
  APPVEYOR_BUILD_WORKER_IMAGE:  test-vs2015-hyperv
  MAX_BUILD_TIME_MINS: 7
  appveyor_build_tests_api_key:
    secure: wJbocyB+OHlu003L0RIgvBpXZVobLawGGNACMvN7DmY=
build:
  verbosity: minimal
  project: build-tests.sln
before_build:
  nuget restore

#after_build:
#  - cmd: C:/Tools/xUnit20/xunit.runner.console.exe "C:/Projects/build-tests/bin/debug/build-tests.dll"
