version: 1.0.{build}

init:
- appveyor version
- git --version

- ps: 'Write-Host "APPVEYOR_BUILD_WORKER_CLOUD: $env:APPVEYOR_BUILD_WORKER_CLOUD"'
- ps: 'Write-Host "APPVEYOR_BUILD_WORKER_IMAGE: $env:APPVEYOR_BUILD_WORKER_IMAGE"'

environment:
  MAX_BUILD_TIME_MINS: 20
  appveyor_build_tests_api_key:
    secure: wJbocyB+OHlu003L0RIgvBpXZVobLawGGNACMvN7DmY=
    
build:
  verbosity: minimal
  project: build-tests.sln
  
before_build:
  nuget restore

#after_build:
#  - cmd: C:/Tools/xUnit20/xunit.runner.console.exe "C:/Projects/build-tests/bin/debug/build-tests.dll"
